// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneDescriptor } from "./SceneDescriptor";

export interface CycleScenesDescriptor { scenes: Array<SceneDescriptor>, nowrap: boolean | null, }