// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Light } from "./Light";
import type { MultiSourceLight } from "./MultiSourceLight";
import type { OnOffDevice } from "./OnOffDevice";
import type { SensorKind } from "./SensorKind";

export type DeviceState = { OnOffDevice: OnOffDevice } | { Light: Light } | { MultiSourceLight: MultiSourceLight } | { Sensor: SensorKind };