// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneId } from "./SceneId";

export interface DeviceSceneState { scene_id: SceneId, activation_time: String, }