// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlattenedSceneConfig } from "./FlattenedSceneConfig";
import type { SceneId } from "./SceneId";

export type FlattenedScenesConfig = Record<SceneId, FlattenedSceneConfig>;