// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Light { power: boolean, brightness: number | null, color: { Hsv: { hue: number, saturation: number, value: number } } | { Cct: { cct: number } } | null, transition_ms: bigint | null, }