// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneDevicesSearchConfig } from "./SceneDevicesSearchConfig";
import type { SceneGroupsConfig } from "./SceneGroupsConfig";

export interface SceneConfig { name: string, devices: SceneDevicesSearchConfig | null, groups: SceneGroupsConfig | null, hidden: boolean | null, }