// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevicesState } from "./DevicesState";
import type { FlattenedGroupsConfig } from "./FlattenedGroupsConfig";
import type { FlattenedScenesConfig } from "./FlattenedScenesConfig";

export interface StateUpdate { devices: DevicesState, scenes: FlattenedScenesConfig, groups: FlattenedGroupsConfig, }