// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceData } from "./DeviceData";
import type { DeviceId } from "./DeviceId";
import type { IntegrationId } from "./IntegrationId";

export interface Device { id: DeviceId, name: string, integration_id: IntegrationId, data: DeviceData, }