// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ct } from "./Ct";
import type { Hs } from "./Hs";
import type { Rgb } from "./Rgb";
import type { Xy } from "./Xy";

export type DeviceColor = Xy | Hs | Rgb | Ct;