// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManagedDevice } from "./ManagedDevice";
import type { SensorDevice } from "./SensorDevice";

export type DeviceData = { Managed: ManagedDevice } | { Sensor: SensorDevice };