// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceColor } from "./DeviceColor";

export interface ManagedDeviceState { power: boolean, brightness: number | null, color: DeviceColor | null, transition_ms: bigint | null, }