// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capabilities } from "./Capabilities";
import type { ManagedDeviceState } from "./ManagedDeviceState";
import type { SceneId } from "./SceneId";

export interface ManagedDevice { scene: SceneId | null, capabilities: Capabilities, state: ManagedDeviceState, }