// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceKey } from "./DeviceKey";
import type { ManagedDeviceState } from "./ManagedDeviceState";

export type SceneDeviceStates = Record<DeviceKey, ManagedDeviceState>;