// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceKey } from "./DeviceKey";
import type { DeviceState } from "./DeviceState";

export type SceneDeviceStates = Record<DeviceKey, DeviceState>;