// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CorrelatedColorTemperature } from "./CorrelatedColorTemperature";

export interface SceneDeviceState { power: boolean, color: String, brightness: number | null, cct: CorrelatedColorTemperature | null, transition_ms: bigint | null, }