// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IntegrationId } from "./IntegrationId";
import type { SceneDeviceConfig } from "./SceneDeviceConfig";

export type SceneDevicesSearchConfig = Record<IntegrationId, Record<string, SceneDeviceConfig>>;