// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceId } from "./DeviceId";
import type { DeviceSceneState } from "./DeviceSceneState";
import type { DeviceState } from "./DeviceState";
import type { IntegrationId } from "./IntegrationId";

export interface Device { id: DeviceId, name: string, integration_id: IntegrationId, scene: DeviceSceneState | null, state: DeviceState, }