// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneDeviceStates } from "./SceneDeviceStates";

export interface FlattenedSceneConfig { name: string, devices: SceneDeviceStates, hidden: boolean | null, }