// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IntegrationActionPayload } from "./IntegrationActionPayload";
import type { IntegrationId } from "./IntegrationId";

export interface IntegrationActionDescriptor { integration_id: IntegrationId, payload: IntegrationActionPayload, }