// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceKey } from "./DeviceKey";
import type { GroupId } from "./GroupId";
import type { SceneId } from "./SceneId";

export interface SceneDescriptor { scene_id: SceneId, device_keys: Array<DeviceKey> | null, group_keys: Array<GroupId> | null, }