// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneDescriptor } from "./SceneDescriptor";
import type { SceneDeviceLink } from "./SceneDeviceLink";
import type { SceneDeviceState } from "./SceneDeviceState";

export type SceneDeviceConfig = SceneDeviceLink | SceneDescriptor | SceneDeviceState;