// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SensorKind = { OnOffSensor: { value: boolean, } } | { DimmerSwitch: { on: boolean, up: boolean, down: boolean, off: boolean, } } | "Unknown";